
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-slave
  namespace: ns-jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-slave
  template:
    metadata:
      labels:
        app: jenkins-slave
    spec:
      containers:
        - name: jenkins-slave
          image: ebraammaher/jenkins:slave
          imagePullPolicy: IfNotPresent
          ports:
            - name: port22
              containerPort: 22

          volumeMounts:            
            - name: dockersock
              mountPath: /var/run/docker.sock
      volumes:        
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock

---
apiVersion: v1
kind: Service
metadata: 
  name: jenkins-slave
  namespace: ns-jenkins
spec: 
  selector: 
    app: jenkins-slave
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22 
